#!/usr/bin/env python3
"""
Script para probar la lectura del Google Sheet localmente.
Muestra exactamente qué filas se están leyendo y cuáles se saltan.
"""
import os
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from logger_config import logger


def test_sheet_reading():
    """Lee el Sheet y muestra estadísticas detalladas."""
    sheet_id = os.getenv('TOPICS_SHEET_ID')
    creds_path = os.getenv('GOOGLE_SHEETS_CREDENTIALS_PATH')

    if not sheet_id:
        print("❌ ERROR: TOPICS_SHEET_ID not set")
        return False

    if not creds_path or not os.path.exists(creds_path):
        print(f"❌ ERROR: GOOGLE_SHEETS_CREDENTIALS_PATH not found at {creds_path}")
        return False

    try:
        from google.oauth2 import service_account
        from googleapiclient.discovery import build

        print("\n" + "="*70)
        print("GOOGLE SHEET READING TEST")
        print("="*70)

        # Connect to Google Sheets
        creds = service_account.Credentials.from_service_account_file(
            creds_path,
            scopes=['https://www.googleapis.com/auth/spreadsheets.readonly']
        )
        service = build('sheets', 'v4', credentials=creds)
        sheets = service.spreadsheets()

        # Read ALL data
        result = sheets.values().get(
            spreadsheetId=sheet_id,
            range='Topics!A2:E'
        ).execute()

        rows = result.get('values', [])
        print(f"\n📊 Total rows in Sheet (excluding header): {len(rows)}")

        # Analyze each row
        valid_topics = []
        skipped_rows = []
        autogenerated_ids = []

        def _generate_id(text: str) -> str:
            """Generate ID from text."""
            import re
            from datetime import datetime
            words = re.findall(r'\w+', text.lower())
            prefix = '-'.join(words[:3]) if words else 'topic'
            timestamp = datetime.utcnow().strftime('%Y%m%d%H%M%S')
            return f"{prefix}-{timestamp}"

        for row_num, row in enumerate(rows, start=2):
            # Handle empty rows
            if not row or len(row) < 1:
                skipped_rows.append({
                    'row_num': row_num,
                    'reason': 'Empty row',
                    'data': row
                })
                continue

            # Get values
            topic_id = (row[0] or '').strip() if len(row) > 0 else ''
            abstract = (row[1] or '').strip() if len(row) > 1 else ''

            # Skip if no abstract
            if not abstract:
                skipped_rows.append({
                    'row_num': row_num,
                    'reason': 'Empty Abstract',
                    'data': row
                })
                continue

            # Auto-generate ID if missing
            if not topic_id:
                topic_id = _generate_id(abstract)
                autogenerated_ids.append({
                    'row_num': row_num,
                    'generated_id': topic_id,
                    'abstract': abstract[:60] + "..." if len(abstract) > 60 else abstract
                })

            valid_topics.append({
                'row_num': row_num,
                'id': topic_id,
                'abstract': abstract[:60] + "..." if len(abstract) > 60 else abstract,
                'autogenerated': not (row[0] or '').strip()
            })

        # Print summary
        print(f"\n✅ Valid topics: {len(valid_topics)}")
        print(f"🔧 Auto-generated IDs: {len(autogenerated_ids)}")
        print(f"❌ Skipped rows: {len(skipped_rows)}")

        # Show first 5 valid topics
        if valid_topics:
            print(f"\n📝 First 5 valid topics:")
            for topic in valid_topics[:5]:
                print(f"  Row {topic['row_num']}: {topic['id']}")
                print(f"    {topic['abstract']}")

        # Show auto-generated IDs
        if autogenerated_ids:
            print(f"\n🔧 Auto-generated IDs (all {len(autogenerated_ids)}):")
            for item in autogenerated_ids:
                print(f"  Row {item['row_num']}: {item['generated_id']}")
                print(f"    {item['abstract']}")

        # Show all skipped rows
        if skipped_rows:
            print(f"\n⚠️  Skipped rows (all {len(skipped_rows)}):")
            for skip in skipped_rows:
                print(f"  Row {skip['row_num']}: {skip['reason']}")
                if skip['data']:
                    print(f"    Data: {skip['data']}")
                else:
                    print(f"    Data: (empty)")

        # Show last 5 valid topics
        if len(valid_topics) > 5:
            print(f"\n📝 Last 5 valid topics:")
            for topic in valid_topics[-5:]:
                print(f"  Row {topic['row_num']}: {topic['id']}")
                print(f"    {topic['abstract']}")

        print("\n" + "="*70)
        print("RECOMMENDATIONS:")
        print("="*70)

        if autogenerated_ids:
            print(f"\n✅ {len(autogenerated_ids)} topics will have auto-generated IDs")
            print("   These will be ingested with IDs like: 'you-don-t-20251110123456'")
            print("   The sync script now auto-generates IDs for rows without them.")
            print("\n   To use custom IDs instead:")
            print("   - Open the Google Sheet and add IDs manually")
            print("   - Or leave blank and let the system generate them")

        if skipped_rows:
            print("\n⚠️  Skipped rows need attention:")
            print("   - These rows have no Abstract (required)")
            print("   - Fill in Abstract or delete the empty rows")

        if not skipped_rows and not autogenerated_ids:
            print("\n✅ All rows have valid IDs and Abstracts! No action needed.")

        print("="*70 + "\n")

        return True

    except ImportError:
        print("\n❌ ERROR: Google API libraries not installed")
        print("   Run: pip install google-auth google-api-python-client")
        return False
    except Exception as e:
        print(f"\n❌ ERROR: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == '__main__':
    success = test_sheet_reading()
    sys.exit(0 if success else 1)
