name: Promote Approved Topics

on:
  schedule:
    - cron: "0 7 * * *" # daily at 07:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  promote:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install promoter dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install python-dotenv requests chromadb

      - name: Promote Notion topics
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          set -euo pipefail
          python promote_notion_topics.py --status Validated --set-status Promoted
