name: Promote Approved Topics

on:
  schedule:
    - cron: "0 7 * * *" # daily at 07:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  promote:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      HF_INGEST_LIMIT: ${{ vars.HF_INGEST_LIMIT }}
      FALLBACK_PROVIDER_ORDER: gemini,openrouter

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.workflow.txt

      - name: Ingest Reddit signals
        run: |
          set -euo pipefail
          LIMIT="${HF_INGEST_LIMIT:-80}"
          python reddit_ingestion.py --limit "$LIMIT" --notify

      - name: Ingest Hugging Face signals
        run: |
          set -euo pipefail
          LIMIT="${HF_INGEST_LIMIT:-50}"
          python hf_ingestion.py --limit "$LIMIT" --notify

      - name: Sync candidates to Notion
        run: |
          set -euo pipefail
          python hf_notion_sync.py --status Review

      - name: Notify pending review count
        run: |
          set -euo pipefail
          python scripts/notion_report.py --status Review --threshold 1

      - name: Promote validated topics
        run: |
          set -euo pipefail
          python scripts/promote_and_notify.py --status Validated --set-status Promoted
